spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/ims
        username: postgres
        password: your_password

    output:
        ansi:
            enabled: ALWAYS

server:
    port: 8080

logging:
    level:
        com:
            skillstorm: debug